// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Calculatoare.Data.Models;

public partial class order_status
{
    public int Id { get; set; }

    public string Status { get; set; }

    public virtual ICollection<order> order { get; set; } = new List<order>();
}