// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Calculatoare.Data.Models;

public partial class order
{
    public int Id { get; set; }

    public string Notes { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime LastModified { get; set; }

    public int CustomerId { get; set; }

    public int? EmployeeId { get; set; }

    public int StatusId { get; set; }

    public virtual user Customer { get; set; }

    public virtual user Employee { get; set; }

    public virtual order_status Status { get; set; }

    public virtual ICollection<order_service> order_service { get; set; } = new List<order_service>();
}