// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Calculatoare.Data.Models;

public partial class order_service
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int ServiceId { get; set; }

    public virtual order Order { get; set; }

    public virtual service Service { get; set; }
}