// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Calculatoare.Data.Models;

public partial class review
{
    public int Id { get; set; }

    public string Notes { get; set; }

    public double Rating { get; set; }

    public int? UserId { get; set; }

    public virtual user User { get; set; }
}