// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Calculatoare.Data.Models;

public partial class service
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public double Price { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<order_service> order_service { get; set; } = new List<order_service>();
}