// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Calculatoare.Data.Models;

public partial class user_detail
{
    public int Id { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Phone { get; set; }

    public string Adress { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public string ZipCode { get; set; }

    public virtual ICollection<user> user { get; set; } = new List<user>();
}