// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Calculatoare.Data.Models;

public partial class user_type
{
    public int Id { get; set; }

    public string Type { get; set; }

    public virtual ICollection<user> user { get; set; } = new List<user>();
}