// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Calculatoare.Data.Models;

public partial class user
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime LastModified { get; set; }

    public bool IsActive { get; set; }

    public int? DetailsId { get; set; }

    public int TypeId { get; set; }

    public virtual user_detail Details { get; set; }

    public virtual user_type Type { get; set; }

    public virtual ICollection<order> orderCustomer { get; set; } = new List<order>();

    public virtual ICollection<order> orderEmployee { get; set; } = new List<order>();

    public virtual ICollection<review> review { get; set; } = new List<review>();
}