// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Calculatoare.Data.Models;
using Microsoft.EntityFrameworkCore;

namespace Calculatoare.Data.Context;

public partial class CalculatoareContext : DbContext
{
    public CalculatoareContext(DbContextOptions<CalculatoareContext> options)
        : base(options)
    {
    }

    public virtual DbSet<order> order { get; set; }

    public virtual DbSet<order_service> order_service { get; set; }

    public virtual DbSet<order_status> order_status { get; set; }

    public virtual DbSet<review> review { get; set; }

    public virtual DbSet<service> service { get; set; }

    public virtual DbSet<user> user { get; set; }

    public virtual DbSet<user_detail> user_detail { get; set; }

    public virtual DbSet<user_type> user_type { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order__3214EC07C392DF18");

            entity.Property(e => e.DateCreated).HasColumnType("datetime");
            entity.Property(e => e.LastModified).HasColumnType("datetime");

            entity.HasOne(d => d.Customer).WithMany(p => p.orderCustomer)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__CustomerI__31B762FC");

            entity.HasOne(d => d.Employee).WithMany(p => p.orderEmployee)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK__order__EmployeeI__32AB8735");

            entity.HasOne(d => d.Status).WithMany(p => p.order)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__StatusId__339FAB6E");
        });

        modelBuilder.Entity<order_service>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order_se__3214EC0721EAD0CA");

            entity.HasOne(d => d.Order).WithMany(p => p.order_service)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order_ser__Order__3864608B");

            entity.HasOne(d => d.Service).WithMany(p => p.order_service)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order_ser__Servi__395884C4");
        });

        modelBuilder.Entity<order_status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order_st__3214EC075E7F8F53");

            entity.Property(e => e.Status).IsRequired();
        });

        modelBuilder.Entity<review>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__review__3214EC07DCD79812");

            entity.HasOne(d => d.User).WithMany(p => p.review)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__review__UserId__2CF2ADDF");
        });

        modelBuilder.Entity<service>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__service__3214EC07306A4933");

            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.Title).IsRequired();
        });

        modelBuilder.Entity<user>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user__3214EC0717688A21");

            entity.Property(e => e.DateCreated).HasColumnType("datetime");
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.Username).IsRequired();

            entity.HasOne(d => d.Details).WithMany(p => p.user)
                .HasForeignKey(d => d.DetailsId)
                .HasConstraintName("FK__user__DetailsId__2A164134");

            entity.HasOne(d => d.Type).WithMany(p => p.user)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user__TypeId__29221CFB");
        });

        modelBuilder.Entity<user_detail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_det__3214EC07EFEA4951");

            entity.Property(e => e.Firstname).IsRequired();
            entity.Property(e => e.Lastname).IsRequired();
            entity.Property(e => e.Phone).IsRequired();
        });

        modelBuilder.Entity<user_type>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_typ__3214EC073BB3FFA3");

            entity.Property(e => e.Type).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}