// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Calculatoare.Data.Models;
using Microsoft.EntityFrameworkCore;

namespace Calculatoare.Data.Context;

public partial class CalculatoareContext : DbContext
{
    public CalculatoareContext(DbContextOptions<CalculatoareContext> options)
        : base(options)
    {
    }

    public virtual DbSet<order> order { get; set; }

    public virtual DbSet<order_service> order_service { get; set; }

    public virtual DbSet<order_status> order_status { get; set; }

    public virtual DbSet<review> review { get; set; }

    public virtual DbSet<service> service { get; set; }

    public virtual DbSet<user> user { get; set; }

    public virtual DbSet<user_detail> user_detail { get; set; }

    public virtual DbSet<user_type> user_type { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order__3214EC075C9CAA97");

            entity.Property(e => e.DateCreated).HasColumnType("datetime");
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.Notes).HasMaxLength(1);

            entity.HasOne(d => d.Customer).WithMany(p => p.orderCustomer)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__CustomerI__1AD3FDA4");

            entity.HasOne(d => d.Employee).WithMany(p => p.orderEmployee)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK__order__EmployeeI__1BC821DD");

            entity.HasOne(d => d.Status).WithMany(p => p.order)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__StatusId__1CBC4616");
        });

        modelBuilder.Entity<order_service>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order_se__3214EC07871AF692");

            entity.HasOne(d => d.Order).WithMany(p => p.order_service)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order_ser__Order__2180FB33");

            entity.HasOne(d => d.Service).WithMany(p => p.order_service)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order_ser__Servi__22751F6C");
        });

        modelBuilder.Entity<order_status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order_st__3214EC07895C49DF");

            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(1);
        });

        modelBuilder.Entity<review>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__review__3214EC070398A983");

            entity.Property(e => e.Notes).HasMaxLength(1);

            entity.HasOne(d => d.User).WithMany(p => p.review)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__review__UserId__160F4887");
        });

        modelBuilder.Entity<service>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__service__3214EC07B5AF4B70");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(1);
        });

        modelBuilder.Entity<user>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user__3214EC0723B0EB4D");

            entity.Property(e => e.DateCreated).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(1);
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(1);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(1);

            entity.HasOne(d => d.Details).WithMany(p => p.user)
                .HasForeignKey(d => d.DetailsId)
                .HasConstraintName("FK__user__DetailsId__1332DBDC");

            entity.HasOne(d => d.Type).WithMany(p => p.user)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user__TypeId__123EB7A3");
        });

        modelBuilder.Entity<user_detail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_det__3214EC071DD17FAD");

            entity.Property(e => e.Adress).HasMaxLength(1);
            entity.Property(e => e.City).HasMaxLength(1);
            entity.Property(e => e.Country).HasMaxLength(1);
            entity.Property(e => e.Firstname)
                .IsRequired()
                .HasMaxLength(1);
            entity.Property(e => e.Lastname)
                .IsRequired()
                .HasMaxLength(1);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(1);
            entity.Property(e => e.ZipCode).HasMaxLength(1);
        });

        modelBuilder.Entity<user_type>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_typ__3214EC07494ED94D");

            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(1);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}